---
headscale_version: "0.22.3"
headscale_arch: "arm64"

headscale_url: "https://github.com/juanfont/headscale/releases/download/v{{ headscale_version }}/headscale_{{ headscale_version }}_linux_{{ headscale_arch }}"
headscale_checksum: "sha256:https://github.com/juanfont/headscale/releases/download/v{{ headscale_version }}/checksums.txt"

headscale_binary: "/usr/bin/headscale"
headscale_workdir: "/var/lib/headscale"
headscale_confdir: "/etc/headscale"
headscale_config: "{{ headscale_confdir }}/config.yaml"
