---
dependency:
  name: galaxy
driver:
  name: molecule-qemu
platforms:
  - name: debian-bullseye-arm64
    image_arch: aarch64
    image_url: https://cloud.debian.org/images/cloud/bullseye/latest/debian-11-genericcloud-arm64.qcow2
    image_checksum: sha512:https://cloud.debian.org/images/cloud/bullseye/latest/SHA512SUMS
    network_mode: user
    network_ssh_port: 2222
provisioner:
  name: ansible
  inventory:
    host_vars:
      debian-bullseye-arm64:
        headscale_workdir: /mnt/local/headscale
        headscale_confdir: /mnt/local/headscale/conf.d
verifier:
  name: testinfra
