---
- name: Assert supported OS
  ansible.builtin.assert:
    that:
      - ansible_distribution in ['Ubuntu', 'Debian']
      - ansible_distribution_release in ['focal', 'jammy', 'bullseye']
    success_msg: "Supported OS detected: {{ ansible_distribution }} {{ ansible_distribution_release }}"
    fail_msg: "Unsupported OS detected: {{ ansible_distribution }} {{ ansible_distribution_release }}"

- name: APT cache update
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install APT dependencies
  ansible.builtin.apt:
    name:
      - gnupg
      - apt-transport-https
      - ca-certificates
    state: present

- name: Add APT key
  ansible.builtin.apt_key:
    url: https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }}/{{ ansible_distribution_release }}.noarmor.gpg
    state: present

- name: Add APT repository
  ansible.builtin.apt_repository:
    repo: "deb https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"
    state: present

- name: Install Tailscale
  ansible.builtin.apt:
    name: tailscale
    state: present

- name: Create Tailscale service
  ansible.builtin.template:
    src: tailscaled.service.j2
    dest: /lib/systemd/system/tailscaled.service
    owner: root
    group: root
    mode: 0644
  register: tailscaled_systemd_service

- name: Enable Tailscale service
  ansible.builtin.systemd:
    name: tailscaled
    enabled: true
    daemon_reload: "{{ tailscaled_systemd_service.changed }}"
    state: "{{ tailscaled_systemd_service.changed | ternary('restarted', 'started') }}"

- name: Wait for Tailscale to be ready
  ansible.builtin.wait_for:
    path: "{{ tailscaled_socket }}"
    state: present
    timeout: 60

- name: Register Tailscale status
  ansible.builtin.command: >-
    tailscale
    --socket {{ tailscaled_socket }}
    status --json
  register: tailscale_status
  changed_when: false

- name: Register Tailscale node
  when: (tailscale_status.stdout | from_json)['BackendState'] == 'NeedsLogin'
  block:
    - name: Assert Tailscale auth key is defined
      ansible.builtin.assert:
        that:
          - tailscale_auth_key is defined
          - tailscale_auth_key != ""
        success_msg: "Tailscale auth key is defined"
        fail_msg: "Tailscale auth key is not defined"

    - name: Register Tailscale node
      ansible.builtin.command: >-
        tailscale
        --socket {{ tailscaled_socket }}
        up
        {% if tailscale_login_server %}
        --login-server {{ tailscale_login_server }}
        {% endif %}
        --auth-key {{ tailscale_auth_key }}
      changed_when: true
