---
- name: Assert supported OS
  ansible.builtin.assert:
    that:
      - ansible_distribution in ['Ubuntu', 'Debian']
      - ansible_distribution_release in ['focal', 'jammy', 'bullseye']

- name: Add APT key
  ansible.builtin.apt_key:
    url: https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }}/{{ ansible_distribution_release }}.noarmor.gpg
    state: present

- name: Add APT repository
  ansible.builtin.apt_repository:
    repo: "deb https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"
    state: present

- name: Install Tailscale
  ansible.builtin.apt:
    name: tailscale
    state: present

- name: Enable Tailscale service
  ansible.builtin.service:
    name: tailscaled
    enabled: true
    state: started

- name: Wait for Tailscale to be ready
  ansible.builtin.wait_for:
    path: /var/run/tailscale/tailscaled.sock
    state: present
    timeout: 60

- name: Register Tailscale status
  ansible.builtin.command: tailscale status --json
  register: tailscale_status
  changed_when: false

- name: Register Tailscale node
  when: (tailscale_status.stdout | from_json)['BackendState'] == 'NeedsLogin'
  block:
    - name: Assert Tailscale auth key is defined
      ansible.builtin.assert:
        that:
          - tailscale_auth_key is defined
          - tailscale_auth_key != ""

    - name: Register Tailscale node
      ansible.builtin.command: >-
        tailscale up
        {% if tailscale_login_server %}
        --login-server {{ tailscale_login_server }}
        {% endif %}
        --auth-key {{ tailscale_auth_key }}
      changed_when: true
