---
- name: Assert that the OS is supported
  ansible.builtin.assert:
    that:
      - ansible_distribution in ['Ubuntu', 'Debian']
      - ansible_distribution_release in ['focal', 'jammy', 'bullseye']

- name: Add APT key
  ansible.builtin.apt_key:
    url: https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }}/{{ ansible_distribution_release }}.noarmor.gpg
    state: present

- name: Add APT repository
  ansible.builtin.apt_repository:
    repo: "deb https://pkgs.tailscale.com/stable/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"
    state: present

- name: Install Tailscale
  ansible.builtin.apt:
    name: tailscale
    state: present

- name: Enable Tailscale service
  ansible.builtin.service:
    name: tailscaled
    enabled: true
    state: started
