---
- name: Assert supported OS
  ansible.builtin.assert:
    that:
      - ansible_distribution in ['Ubuntu', 'Debian']
      - ansible_distribution_release in ['focal', 'jammy', 'bullseye']
    success_msg: "Supported OS detected: {{ ansible_distribution }} {{ ansible_distribution_release }}"
    fail_msg: "Unsupported OS detected: {{ ansible_distribution }} {{ ansible_distribution_release }}"

- name: APT cache update
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Download Headscale binary
  ansible.builtin.get_url:
    url: "{{ headscale_url }}"
    checksum: "{{ headscale_checksum }}"
    dest: "{{ headscale_binary }}"
    mode: 0755

- name: Create Headscale directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - "{{ headscale_workdir }}"
    - "{{ headscale_confdir }}"

- name: Create Headscale config
  ansible.builtin.template:
    src: config.yaml.j2
    dest: "{{ headscale_config }}"
    owner: root
    group: root
    mode: 0644

- name: Create Headscale service
  ansible.builtin.template:
    src: headscale.service.j2
    dest: /usr/lib/systemd/system/headscale.service
    owner: root
    group: root
    mode: 0644
  register: headscale_systemd_service

- name: Enable Headscale service
  ansible.builtin.systemd:
    name: headscale
    enabled: true
    daemon_reload: "{{ headscale_systemd_service.changed }}"
    state: "{{ headscale_systemd_service.changed | ternary('restarted', 'started') }}"
