---
- name: Converge
  hosts: all
  gather_facts: true

  environment:
    http_proxy: "{{ lookup('ansible.builtin.env', 'http_proxy') | default(omit) }}"
    https_proxy: "{{ lookup('ansible.builtin.env', 'https_proxy') | default(omit) }}"

  tasks:
    - name: Get auth key  # noqa: run-once[task]
      ansible.builtin.shell: |
        set -euo pipefail
        headscale users create molecule || true
        headscale preauthkeys create -u molecule
      args:
        executable: /bin/bash
      delegate_to: headscale
      run_once: true
      register: headscale_auth_key
      changed_when: false

    - name: Set auth key
      ansible.builtin.set_fact:
        tailscale_auth_key: "{{ headscale_auth_key.stdout_lines[-1] }}"
      delegate_to: tailscale

- name: Converge
  hosts: tailscale
  gather_facts: true

  environment:
    http_proxy: "{{ lookup('ansible.builtin.env', 'http_proxy') | default(omit) }}"
    https_proxy: "{{ lookup('ansible.builtin.env', 'https_proxy') | default(omit) }}"

  tasks:
    - name: "Include tailscale"
      ansible.builtin.include_role:
        name: "tailscale"
      vars:
        tailscale_login_server: "http://{{ hostvars['headscale']['ansible_host'] }}:8514"
